{"name":"test_case","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [${CARD_WE}] but found [6236330015300082792]","trace":"java.lang.AssertionError: expected [${CARD_WE}] but found [6236330015300082792]\r\n\tat org.testng.Assert.fail(Assert.java:94)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:494)\r\n\tat org.testng.Assert.assertEquals(Assert.java:123)\r\n\tat org.testng.Assert.assertEquals(Assert.java:165)\r\n\tat com.portal.base.utils.AssertUtils.assertRespKeyInfo(AssertUtils.java:47)\r\n\tat com.portal.base.testCase.All_Test_Case.test_case(All_Test_Case.java:56)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:714)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:767)\r\n\tat org.testng.TestRunner.run(TestRunner.java:617)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:348)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:254)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1149)\r\n\tat org.testng.TestNG.run(TestNG.java:1057)\r\n\tat org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"arg0","value":"ApiCaseDetail [caseId=业务-WE卡, apiId=WE卡信息查询,describe=查询核对WE卡返回信息内容\n1、卡号\n2、卡片状态\n3、客户状态\n4、账户状态\n5、开户时间, requestData={\"CARD_NUMBER\":${CARD_WE}}, actualResp=, expectedRespKeyInfo=[{\"jsonPath\":\"$.code\",\"expected\":\"0\"},\n{\"jsonPath\":\"$.msg\",\"expected\":\"请求成功\"},\n{\"jsonPath\":\"$.result.result.CARD_NUMBER\",\"expected\":\"${CARD_WE}\"},\n{\"jsonPath\":\"$.result.result.CARD_ATTR_DESC\",\"expected\":\"正常\"},\n{\"jsonPath\":\"$.result.result.ACCOUNT_ATTR_DESC\",\"expected\":\"账户异常,证件信息异常,风险管控\"},\n{\"jsonPath\":\"$.result.result.CUST_ATTR_DESC\",\"expected\":\"账户异常\"},\n{\"jsonPath\":\"$.result.result.OPENDATE\",\"expected\":\"20181120\"}], extractRespData=, apiInfo=ApiInfo [apiId=WE卡信息查询, apiName=WE卡信息查询, url=http://m1.test-adm.weoa.com/rcs-ucsa/weCard/getWeCard, type=POST, headers=[{\"name\":\"Content-Type\",\"value\":\"application/json;charset=UTF-8\"}], auth=null], beforeCheckerList=null, afterCheckerList=null, getRowNo()=11]"}],"start":1573638756395,"stop":1573638756483,"uuid":"b8a76081-8e88-48ff-b04c-bbf6ebb111ee","historyId":"4483f5dc1925609d6a7e2739913cc24f","fullName":"com.portal.base.testCase.All_Test_Case.test_case","labels":[{"name":"package","value":"com.portal.base.testCase.All_Test_Case"},{"name":"testClass","value":"com.portal.base.testCase.All_Test_Case"},{"name":"testMethod","value":"test_case"},{"name":"parentSuite","value":"Suite"},{"name":"suite","value":"all-test"},{"name":"subSuite","value":"com.portal.base.testCase.All_Test_Case"},{"name":"host","value":"VWBXINGLIOA1"},{"name":"thread","value":"145788@VWBXINGLIOA1.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[]}